### ISSUE TITLE
replicate ls shows step 0 if step is not defined in checkpoints

### ISSUE THREAD

**Issue by andreasjansson** [replicate/replicate#276] opened 2020-11-06 16:56 UTC
```
$ replicate -R  gs://replicate-logo-generation list
═══╡ Fetching new data from "gs://replicate-logo-generation"...
EXPERIMENT  STARTED         STATUS   LOSS_NAME  ROTATE_DEGREES  LATEST CHECKPOINT  LOSS    BEST CHECKPOINT   LOSS
7de7c82     8 minutes ago   running  mse        0               0370371 (step 0)   2.4936  4c994fb (step 0)  1.9617  
99e3d84     4 minutes ago   running  mse        20              b4d876d (step 0)   168.19  b4d876d (step 0)  168.19  
fa320b6     24 seconds ago  running  bce        0               1f09da0 (step 0)   1187.7  e81a79d (step 0)  1151.7  
```

My preference is auto-incrementing `step` if it's undefined, instead of just hiding `step` from the `ls` output.

**Comment by bfirsh** [comment] 2020-11-07 17:26
dupe of #189. This has more detail so will close other one.

**Comment by justinchuby** [comment] 2021-01-01 23:37
Can I take this one?

**Closed** 2021-01-04 15:43 UTC
Labels: good first issue, help wanted, priority/low, type/bug
